---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: headlamp
  namespace: monitoring
spec:
  interval: 15m
  url: https://kubernetes-sigs.github.io/headlamp/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: monitoring
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: headlamp
      version: '0.40.*'
      sourceRef:
        kind: HelmRepository
        name: headlamp
      interval: 5m
  releaseName: headlamp
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    replicaCount: 1