---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 15m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '81.5.*'
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
      interval: 5m
  releaseName: kube-prometheus-stack
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    replicaCount: 1
    grafana:
      envValueFrom:
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID:
          secretKeyRef:
            name: grafana-oauth
            key: client-id
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
          secretKeyRef:
            name: grafana-oauth
            key: client-secret
      "grafana.ini":
        server:
          root_url: https://grafana.swaren.se/
        "auth.generic_oauth":
          enabled: true
          name: Keycloak
          allow_sign_up: true
          scopes: openid email profile
          auth_url: https://auth.swaren.se/realms/segel-cluster/protocol/openid-connect/auth
          token_url: https://auth.swaren.se/realms/segel-cluster/protocol/openid-connect/token
          api_url: https://auth.swaren.se/realms/segel-cluster/protocol/openid-connect/userinfo
          use_pkce: true
          allow_assign_grafana_admin: true
          role_attribute_path: "contains(resource_access.\"grafana-oauth\".roles[*], 'admin') && 'GrafanaAdmin' || contains(resource_access.\"grafana-oauth\".roles[*], 'editor') && 'Editor' || 'Viewer'"