---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sms-backend
  namespace: monitoring
spec:
  interval: 1m
  timeout: 5m
  chart:
    spec:
      chart: SMS.Backend/chart
      sourceRef:
        kind: GitRepository
        name: sms
        namespace: flux-system
      interval: 5m
  releaseName: sms-backend
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: Secret
      name: sms-backend-db
      valuesKey: DATABASE_URL
      targetPath: databaseUrl
  values:
    warehouseUrl: http://sms-warehouse:8081
    image:
      pullPolicy: Always
